name = "cglean"
defaultTargets = ["CGLean"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.8.0-rc1"

[[require]]
name = "leancolls"
git = "https://github.com/mdgeorge4153/LeanColls.git"
rev = "lean-4.8"

[[require]]
name = "ray"
git = "https://github.com/girving/ray.git"
rev = "lean-4.8"

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"
rev = "lean4.8.0-rc1"

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"

[[require]]
name = "«doc-gen4»"
git = "https://github.com/leanprover/doc-gen4"
rev = "main"

[[lean_lib]]
name = "CGLean"
